#!/usr/bin/env python3
"""
eco_train_v2.py — Two-phase ecological reasoning trainer.

Incorporates lessons from Kaggle Nemotron 3rd place (0.900) + silver solutions:
  - Two-phase training: Train (aggressive) → Nudge (precise)
  - Architecture-aware LoRA (Mamba in/out_proj + attention + MLP/MoE + lm_head)
  - LoRA params in fp32 for precision (3rd place technique)
  - Completion-only loss (3rd place: only train on response tokens)
  - NEFTune embedding noise for robustness (VCDAD silver)
  - Stratified sampling by ecological method
  - MoE gradient-sum tying (3rd place variant)
  - Pure BF16 base model (no quantization)

Dataset: ecoreasoner-cot-20k (filtered) — ecological reasoning CoT traces
         generated by DeepSeek R1:14b from PubMed/GBIF/arXiv papers.

Usage (Slurm):
    See hpc/eco_train_v2.slurm

Environment variables:
    M               — model path (HF name or local)
    DATA            — training JSONL path
    OUT             — output directory for adapters
    TARGET_TOTAL    — total training steps (default: 500)
    STEPS_PER_JOB   — steps per Slurm job (default: 250)
    SEQ_LEN         — max sequence length (default: 4096)
    GRAD_ACCUM      — gradient accumulation steps (default: 4)
    LORA_RANK       — LoRA rank (default: 32)
    LORA_ALPHA      — LoRA alpha (default: 32)
    LR              — Phase 1 learning rate (default: 2e-4)
    NUDGE_LR        — Phase 2 learning rate (default: 5e-6)
    NUDGE_FRAC      — fraction of steps for Phase 2 (default: 0.3)
    NEFTUNE_ALPHA   — NEFTune noise alpha (default: 5.0)
    EXPERT_FREEZE_FRAC — fraction of steps to freeze expert LoRA (default: 0.0)
    LORA_FP32       — cast LoRA params to fp32 (default: 1, from 3rd place)
    COMPLETION_ONLY — train only on response tokens (default: 1, from 3rd place)
    INCLUDE_LM_HEAD — include lm_head in LoRA targets (default: 1, from 3rd place)
"""
import os
import re
import sys
import time
import glob
import json
import math
import random
from collections import defaultdict

import torch

# --------------------------------------------------------------------------- env
def _envint(*names, default=0):
    for n in names:
        v = os.environ.get(n)
        if v is not None and v != "":
            return int(v)
    return default

def _envfloat(*names, default=0.0):
    for n in names:
        v = os.environ.get(n)
        if v is not None and v != "":
            return float(v)
    return default

RANK       = _envint("RANK", "SLURM_PROCID", default=0)
LOCAL_RANK = _envint("LOCAL_RANK", "SLURM_LOCALID", default=0)
WORLD_SIZE = _envint("WORLD_SIZE", "SLURM_NTASKS", default=1)
os.environ["RANK"] = str(RANK)
os.environ["LOCAL_RANK"] = str(LOCAL_RANK)
os.environ["WORLD_SIZE"] = str(WORLD_SIZE)
os.environ.setdefault("MASTER_ADDR", "127.0.0.1")
os.environ.setdefault("MASTER_PORT", "29500")
IS_MAIN = RANK == 0

def log(*a):
    if IS_MAIN:
        print(*a, flush=True)

torch.cuda.set_device(LOCAL_RANK)

M             = os.environ["M"]
DATA          = os.environ["DATA"]
OUT           = os.environ["OUT"]
TARGET_TOTAL  = _envint("TARGET_TOTAL", default=500)
STEPS_PER_JOB = _envint("STEPS_PER_JOB", default=250)
SEQ_LEN       = _envint("SEQ_LEN", default=4096)
GRAD_ACCUM    = _envint("GRAD_ACCUM", default=4)
RANK_LORA     = _envint("LORA_RANK", default=32)
ALPHA_LORA    = _envint("LORA_ALPHA", default=32)
LR            = _envfloat("LR", default=2e-4)
NUDGE_LR      = _envfloat("NUDGE_LR", default=5e-6)
NUDGE_FRAC    = _envfloat("NUDGE_FRAC", default=0.3)
NEFTUNE_ALPHA = _envfloat("NEFTUNE_ALPHA", default=5.0)
FREEZE_FRAC   = _envfloat("EXPERT_FREEZE_FRAC", default=0.0)
LORA_FP32     = _envint("LORA_FP32", default=1)
COMPLETION_ONLY = _envint("COMPLETION_ONLY", default=1)
INCLUDE_LM_HEAD = _envint("INCLUDE_LM_HEAD", default=1)

log(f"=== ECO TRAIN V2 | world={WORLD_SIZE} rank={RANK} local={LOCAL_RANK} ===")
log(f"  model={M}")
log(f"  data={DATA} seq={SEQ_LEN}")
log(f"  Phase1: lr={LR}, no clipping")
log(f"  Phase2: lr={NUDGE_LR}, frac={NUDGE_FRAC}")
log(f"  NEFTune={NEFTUNE_ALPHA}, r={RANK_LORA}, alpha={ALPHA_LORA}")
log(f"  grad_accum={GRAD_ACCUM}, target={TARGET_TOTAL}")
log(f"  lora_fp32={bool(LORA_FP32)}, completion_only={bool(COMPLETION_ONLY)}, lm_head={bool(INCLUDE_LM_HEAD)}")

# --------------------------------------------------------------------------- model
from transformers import AutoTokenizer, AutoModelForCausalLM

tok = AutoTokenizer.from_pretrained(M, trust_remote_code=True, local_files_only=True)
if tok.pad_token is None:
    tok.pad_token = tok.eos_token

t0 = time.time()
model = AutoModelForCausalLM.from_pretrained(
    M, trust_remote_code=True, dtype=torch.bfloat16,
    device_map={"": LOCAL_RANK}, low_cpu_mem_usage=True,
    local_files_only=True)
model.config.use_cache = False
log(f"MODEL LOADED in {time.time()-t0:.0f}s on cuda:{LOCAL_RANK} "
    f"{torch.cuda.get_device_name(LOCAL_RANK)}")

# --------------------------------------------------------------------------- LoRA
from peft import LoraConfig, get_peft_model

# Architecture-aware targets: Mamba-2 (in/out_proj) + attention + MLP/MoE + lm_head
candidate_modules = {"q_proj", "k_proj", "v_proj", "o_proj",
                     "gate_proj", "up_proj", "down_proj", "in_proj", "out_proj"}
if INCLUDE_LM_HEAD:
    candidate_modules.add("lm_head")  # 3rd place included lm_head
target = sorted({n.split(".")[-1] for n, m in model.named_modules()
                 if isinstance(m, torch.nn.Linear)} & candidate_modules)
log(f"LoRA target modules: {target}")

peft_config = LoraConfig(
    r=RANK_LORA, lora_alpha=ALPHA_LORA, target_modules=target,
    lora_dropout=0.0, bias="none", task_type="CAUSAL_LM")
model = get_peft_model(model, peft_config)
model.enable_input_require_grads()

# 3rd place technique: cast LoRA params to fp32 for higher precision
if LORA_FP32:
    fp32_count = 0
    for name, param in model.named_parameters():
        if ".lora_" in name and param.requires_grad:
            param.data = param.data.to(torch.float32)
            fp32_count += 1
    log(f"Cast {fp32_count} LoRA params to fp32 (3rd place technique)")

# --------------------------------------------------------- MoE gradient-sum tying
# 3rd place technique: instead of sharing parameter objects, SUM gradients across
# experts per step. This preserves per-expert params but enforces gradient coherence.
# Pattern: tie (up_proj.lora_A) and (down_proj.lora_B) across experts.

def _build_moe_tie_hooks(model, enabled=True):
    """3rd place MoE gradient-sum tying (YS-L implementation)."""
    if not enabled:
        return lambda: None
    moe_tied_params = []
    w1_names = ("gate_up_proj", "up_proj", "gate_proj", ".w1.")
    w2_names = ("down_proj", ".w2.")
    for name, param in model.named_parameters():
        if not param.requires_grad:
            continue
        if ".experts." not in name or ".lora_" not in name:
            continue
        is_w1 = any(part in name for part in w1_names)
        is_w2 = any(part in name for part in w2_names)
        is_a = ".lora_A." in name
        is_b = ".lora_B." in name
        should_tie = (is_w1 and is_a) or (is_w2 and is_b)
        if should_tie and param.dim() >= 2 and param.shape[0] > 1:
            moe_tied_params.append(param)

    # Init: average params across experts
    with torch.no_grad():
        for param in moe_tied_params:
            mean = param.data.mean(dim=0, keepdim=True)
            param.data.copy_(mean.expand_as(param.data))
    log(f"MoE gradient-sum tying: {len(moe_tied_params)} params identified")

    def _tie_grads():
        with torch.no_grad():
            for param in moe_tied_params:
                if param.grad is None:
                    continue
                grad_sum = param.grad.sum(dim=0, keepdim=True)
                param.grad.copy_(grad_sum.expand_as(param.grad))

    return _tie_grads

tie_grads_fn = _build_moe_tie_hooks(model, enabled=True)

trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
log(f"Trainable params after tying: {trainable/1e6:.2f}M")

# Expert-LoRA params for staged freeze
expert_lora_params = [p for n, p in model.named_parameters()
                      if p.requires_grad and ".experts." in n and ".lora_" in n]

# --------------------------------------------------------------------------- data
from datasets import Dataset

ds = Dataset.from_json(DATA)

def fmt(ex):
    ms = ex.get("messages") or [{"role": "user", "content": ex.get("prompt", "?")},
                                {"role": "assistant", "content": ex.get("answer", "?")}]
    result = {"method": ex.get("method", "other")}
    if COMPLETION_ONLY:
        # For completion-only loss, pass messages list so SFTTrainer masks prompt tokens
        result["messages"] = ms
    else:
        result["text"] = tok.apply_chat_template(ms, tokenize=False, add_generation_prompt=False)
    return result

keep_cols = ["method", "messages"] if COMPLETION_ONLY else ["method"]
ds = ds.map(fmt, remove_columns=[c for c in ds.column_names if c not in keep_cols])
log(f"{len(ds)} training records")

# Extract method labels for stratification
method_labels = [ex["method"] for ex in ds]
method_dist = defaultdict(int)
for m in method_labels:
    method_dist[m] += 1
log(f"Method distribution: {dict(sorted(method_dist.items(), key=lambda x: -x[1])[:15])}")

# ------------------------------------------------------- stratified sampler
def build_stratified_index_order(labels, batch_size, seed):
    """Round-robin stratified sampling across categories."""
    by_label = defaultdict(list)
    for idx, label in enumerate(labels):
        by_label[label].append(idx)

    rng = random.Random(seed)
    for idx_list in by_label.values():
        rng.shuffle(idx_list)

    n_batches = max(1, math.ceil(len(labels) / batch_size))
    batches = [[] for _ in range(n_batches)]
    b_order = list(range(n_batches))
    rng.shuffle(b_order)

    assigned = 0
    for label in sorted(by_label.keys()):
        for idx in by_label[label]:
            batches[b_order[assigned % n_batches]].append(idx)
            assigned += 1

    order = [idx for batch in batches for idx in batch]
    return order

from torch.utils.data import Sampler

class PrecomputedOrderSampler(Sampler):
    def __init__(self, order):
        self.order = list(order)
    def __iter__(self):
        return iter(self.order)
    def __len__(self):
        return len(self.order)

# --------------------------------------------------------------------------- resume
ckpts = sorted(glob.glob(os.path.join(OUT, "checkpoint-*", "trainer_state.json")),
               key=os.path.getmtime)
RESUME = os.path.dirname(ckpts[-1]) if ckpts else None
global_step = json.load(open(ckpts[-1])).get("global_step", 0) if ckpts else 0
batch_steps = min(STEPS_PER_JOB, TARGET_TOTAL - global_step)
target_step = global_step + batch_steps

# Manual adapter load: bypass PEFT's broken resume_from_checkpoint path
# (avoids WeightConverter 'distributed_operation' TypeError)
MANUAL_RESUME = False
STEP_OFFSET = 0
if RESUME:
    adapter_sf = os.path.join(RESUME, "adapter_model.safetensors")
    adapter_bin = os.path.join(RESUME, "adapter_model.bin")
    adapter_path = adapter_sf if os.path.exists(adapter_sf) else (
        adapter_bin if os.path.exists(adapter_bin) else None)
    if adapter_path:
        try:
            # Load to CPU first to avoid doubling GPU memory
            if adapter_path.endswith(".safetensors"):
                from safetensors.torch import load_file
                state = load_file(adapter_path, device="cpu")
            else:
                state = torch.load(adapter_path, map_location="cpu")
            log(f"Loaded {len(state)} tensors from {os.path.basename(adapter_path)}")

            # Method 1: PEFT set_peft_model_state_dict (handles key prefix mapping)
            try:
                from peft import set_peft_model_state_dict
                set_peft_model_state_dict(model, state)
                log(f"MANUAL ADAPTER LOAD via set_peft_model_state_dict: "
                    f"{len(state)} tensors from {os.path.basename(RESUME)}")
                MANUAL_RESUME = True
                STEP_OFFSET = global_step
            except Exception as e_peft:
                log(f"set_peft_model_state_dict failed: {e_peft}")
                # Method 2: direct load with auto prefix detection
                model_keys = set(model.state_dict().keys())
                ckpt_keys = set(state.keys())
                direct_match = len(model_keys & ckpt_keys)

                # Try adding base_model.model. prefix (PEFT saves without it)
                prefixed = {f"base_model.model.{k}": v for k, v in state.items()}
                prefix_match = len(model_keys & set(prefixed.keys()))

                if prefix_match > direct_match and prefix_match > 100:
                    state_to_load = prefixed
                    log(f"Added 'base_model.model.' prefix: {prefix_match} keys match")
                elif direct_match > 100:
                    state_to_load = state
                    log(f"Direct key match: {direct_match} keys")
                else:
                    # Try stripping prefix
                    stripped = {}
                    for k, v in state.items():
                        nk = k.replace("base_model.model.", "", 1) if k.startswith("base_model.model.") else k
                        stripped[nk] = v
                    strip_match = len(model_keys & set(stripped.keys()))
                    if strip_match > direct_match:
                        state_to_load = stripped
                        log(f"Stripped prefix: {strip_match} keys match")
                    else:
                        state_to_load = state
                        log(f"No prefix strategy helped (direct={direct_match})")

                # Move to GPU and load
                state_to_load = {k: v.to(f"cuda:{LOCAL_RANK}") for k, v in state_to_load.items()}
                incomp = model.load_state_dict(state_to_load, strict=False)
                matched = len(state_to_load) - len(incomp.unexpected_keys)
                log(f"FALLBACK ADAPTER LOAD: matched={matched}/{len(state_to_load)}, "
                    f"unexpected={len(incomp.unexpected_keys)}")
                if matched > 100:
                    MANUAL_RESUME = True
                    STEP_OFFSET = global_step
                else:
                    log(f"WARNING: Only {matched} keys matched — adapter load ineffective")

            # Free temp state to reclaim memory
            del state
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

        except Exception as e:
            log(f"WARNING: manual adapter load failed: {e}")
            log("Falling back to native trainer resume")
    else:
        log(f"WARNING: no adapter weights found in {RESUME}")

if MANUAL_RESUME:
    log(f"MANUAL RESUME step {global_step} -> {target_step} (offset={STEP_OFFSET})")
    RESUME = None  # disable native resume since we loaded weights manually
elif RESUME:
    log(f"NATIVE RESUME step {global_step} -> {target_step}")
else:
    log(f"FRESH START -> {target_step}")

# --------------------------------------------------------- staged freeze callback
from transformers import TrainerCallback

class ExpertFreezeCallback(TrainerCallback):
    def __init__(self, params, freeze_until):
        self.params = params
        self.freeze_until = freeze_until
    def on_pre_optimizer_step(self, args, state, control, **kw):
        if state.global_step < self.freeze_until:
            for p in self.params:
                if p.grad is not None:
                    p.grad.zero_()
        return control

class MoEGradTieCallback(TrainerCallback):
    """Apply gradient-sum tying before each optimizer step (3rd place)."""
    def __init__(self, tie_fn):
        self.tie_fn = tie_fn
    def on_pre_optimizer_step(self, args, state, control, **kw):
        self.tie_fn()
        return control

freeze_until = int(math.ceil(TARGET_TOTAL * FREEZE_FRAC)) if FREEZE_FRAC > 0 else 0
callbacks = []
if freeze_until > 0:
    callbacks.append(ExpertFreezeCallback(expert_lora_params, freeze_until))
    log(f"Staged expert-LoRA freeze ON: frozen until step {freeze_until}")

callbacks.append(MoEGradTieCallback(tie_grads_fn))
log("MoE gradient-sum tying callback registered")

# --------------------------------------------------------------- two-phase setup
# Phase boundary: steps for Phase 1 vs Phase 2
nudge_start = int(TARGET_TOTAL * (1.0 - NUDGE_FRAC))

class TwoPhaseCallback(TrainerCallback):
    """Switch hyperparameters at the phase boundary.
    Phase 1: high LR, no gradient clipping
    Phase 2: low LR (nudge), gradient clipping ON, cosine schedule
    """
    def __init__(self, nudge_start, nudge_lr, phase1_lr, step_offset=0):
        self.nudge_start = nudge_start
        self.nudge_lr = nudge_lr
        self.phase1_lr = phase1_lr
        self.step_offset = step_offset
        self.switched = False

    def on_step_begin(self, args, state, control, **kw):
        real_step = state.global_step + self.step_offset
        if not self.switched and real_step >= self.nudge_start:
            self.switched = True
            # Switch to nudge LR
            optimizer = kw.get("optimizer")
            if optimizer is not None:
                for pg in optimizer.param_groups:
                    pg["lr"] = self.nudge_lr
            # Re-enable gradient clipping
            args.max_grad_norm = 1.0
            if IS_MAIN:
                print(f"\n{'='*60}", flush=True)
                print(f"PHASE 2 NUDGE START at step {state.global_step}", flush=True)
                print(f"  lr: {self.phase1_lr} -> {self.nudge_lr}", flush=True)
                print(f"  max_grad_norm: 1e9 -> 1.0", flush=True)
                print(f"{'='*60}\n", flush=True)
        return control

callbacks.append(TwoPhaseCallback(nudge_start, NUDGE_LR, LR, step_offset=STEP_OFFSET))
log(f"Two-phase: Phase1 steps 0-{nudge_start}, Phase2 steps {nudge_start}-{TARGET_TOTAL}")

# ------------------------------------------------------------------- SFT training
from trl import SFTTrainer, SFTConfig

warmup_steps = min(30, max(1, target_step // 10))
eff_batch = 1 * GRAD_ACCUM * WORLD_SIZE

# When using manual resume, train for batch_steps only (trainer starts from step 0)
cfg_max_steps = batch_steps if MANUAL_RESUME else target_step
# Use a sub-directory for Phase 2 intermediate checkpoints to avoid overwriting Phase 1
cfg_output_dir = os.path.join(OUT, f"phase2_from_{global_step}") if MANUAL_RESUME else OUT
if MANUAL_RESUME:
    os.makedirs(cfg_output_dir, exist_ok=True)

cfg = SFTConfig(
    output_dir=cfg_output_dir,
    max_steps=cfg_max_steps,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=GRAD_ACCUM,
    learning_rate=LR,
    lr_scheduler_type="linear",
    warmup_steps=warmup_steps,
    logging_steps=10,
    bf16=True,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    optim="adamw_torch",
    max_length=SEQ_LEN,
    dataset_text_field=None if COMPLETION_ONLY else "text",
    packing=False,
    save_steps=50,
    save_total_limit=15,
    report_to="none",
    adam_beta1=0.9,
    adam_beta2=0.95,
    adam_epsilon=1e-8,
    weight_decay=0.0,
    max_grad_norm=1e9,  # Phase 1: clipping OFF (from VCDAD silver solution)
    neftune_noise_alpha=NEFTUNE_ALPHA,  # NEFTune embedding noise (from VCDAD)
    use_liger_kernel=False,  # liger may not be installed in all venvs
    ddp_find_unused_parameters=True,
    dataloader_num_workers=0,  # 0 avoids /dev/shm Bus error on HPC nodes
    seed=42,
)

# Build stratified order
strat_order = build_stratified_index_order(method_labels, eff_batch, seed=42)

# Custom SFTTrainer with stratified sampling
class StratifiedSFTTrainer(SFTTrainer):
    def __init__(self, *args, stratified_order=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.stratified_order = stratified_order

    def get_train_dataloader(self):
        if self.stratified_order is None:
            return super().get_train_dataloader()
        from torch.utils.data import DataLoader
        dataloader_kwargs = {
            "batch_size": self.args.per_device_train_batch_size,
            "sampler": PrecomputedOrderSampler(self.stratified_order),
            "collate_fn": self.data_collator,
            "num_workers": self.args.dataloader_num_workers,
            "pin_memory": self.args.dataloader_pin_memory,
            "drop_last": self.args.dataloader_drop_last,
        }
        if self.args.dataloader_num_workers > 0:
            dataloader_kwargs["prefetch_factor"] = self.args.dataloader_prefetch_factor
        return DataLoader(self.train_dataset, **dataloader_kwargs)

trainer = StratifiedSFTTrainer(
    model=model, args=cfg, train_dataset=ds,
    processing_class=tok, callbacks=callbacks,
    stratified_order=strat_order,
)

log(f"TRAINING [ECO V2 TWO-PHASE]: {global_step} -> {target_step} | eff_batch="
    f"{eff_batch} (1 x ga{GRAD_ACCUM} x {WORLD_SIZE} gpu)")
log(f"  Phase1: lr={LR}, no clipping, steps 0-{nudge_start}")
log(f"  Phase2: lr={NUDGE_LR}, clipping=1.0, steps {nudge_start}-{TARGET_TOTAL}")
log(f"  NEFTune alpha={NEFTUNE_ALPHA}")

t0 = time.time()
try:
    trainer.train(resume_from_checkpoint=RESUME)
except TypeError as e:
    if "distributed_operation" in str(e) or "WeightConverter" in str(e):
        log(f"PEFT resume bug hit: {e}")
        log("Native resume failed — use manual adapter load (already handled above).")
        log("If this fires, the manual load path was skipped. Aborting.")
        sys.exit(1)
    raise
elapsed = (time.time() - t0) / 60
final_loss = next((e["loss"] for e in reversed(trainer.state.log_history) if "loss" in e), "?")
log(f"DONE {elapsed:.1f}min loss={final_loss}")

if IS_MAIN:
    model.save_pretrained(os.path.join(OUT, f"checkpoint-{target_step}"))
    print(f"Adapter saved to checkpoint-{target_step}", flush=True)
    if target_step < TARGET_TOTAL:
        print(f"NEED_RESUBMIT: target_step={target_step} target_total={TARGET_TOTAL}", flush=True)
    else:
        print(f"TARGET_REACHED: {target_step}/{TARGET_TOTAL}", flush=True)
    print("SUCCESS", flush=True)
