#!/usr/bin/env python3
"""
eco_train_v2.py — Two-phase ecological reasoning trainer.

Incorporates lessons from Kaggle Nemotron winning solutions:
  - Two-phase training: Train (aggressive) → Nudge (precise)
  - Architecture-aware LoRA (Mamba in/out_proj + attention + MLP/MoE)
  - NEFTune embedding noise for robustness
  - Stratified sampling by ecological method
  - Pure BF16 (no quantization)
  - MoE weight tying (from our tied_train.py)

Dataset: ecoreasoner-cot-20k (filtered) — ecological reasoning CoT traces
         generated by DeepSeek R1:14b from PubMed/GBIF/arXiv papers.

Usage (Slurm):
    See hpc/eco_train_v2.slurm

Environment variables:
    M               — model path (HF name or local)
    DATA            — training JSONL path
    OUT             — output directory for adapters
    TARGET_TOTAL    — total training steps (default: 500)
    STEPS_PER_JOB   — steps per Slurm job (default: 250)
    SEQ_LEN         — max sequence length (default: 4096)
    GRAD_ACCUM      — gradient accumulation steps (default: 4)
    LORA_RANK       — LoRA rank (default: 32)
    LORA_ALPHA      — LoRA alpha (default: 32)
    LR              — Phase 1 learning rate (default: 2e-4)
    NUDGE_LR        — Phase 2 learning rate (default: 5e-6)
    NUDGE_FRAC      — fraction of steps for Phase 2 (default: 0.3)
    NEFTUNE_ALPHA   — NEFTune noise alpha (default: 5.0)
    EXPERT_FREEZE_FRAC — fraction of steps to freeze expert LoRA (default: 0.0)
"""
import os
import re
import sys
import time
import glob
import json
import math
import random
from collections import defaultdict

import torch

# --------------------------------------------------------------------------- env
def _envint(*names, default=0):
    for n in names:
        v = os.environ.get(n)
        if v is not None and v != "":
            return int(v)
    return default

def _envfloat(*names, default=0.0):
    for n in names:
        v = os.environ.get(n)
        if v is not None and v != "":
            return float(v)
    return default

RANK       = _envint("RANK", "SLURM_PROCID", default=0)
LOCAL_RANK = _envint("LOCAL_RANK", "SLURM_LOCALID", default=0)
WORLD_SIZE = _envint("WORLD_SIZE", "SLURM_NTASKS", default=1)
os.environ["RANK"] = str(RANK)
os.environ["LOCAL_RANK"] = str(LOCAL_RANK)
os.environ["WORLD_SIZE"] = str(WORLD_SIZE)
os.environ.setdefault("MASTER_ADDR", "127.0.0.1")
os.environ.setdefault("MASTER_PORT", "29500")
IS_MAIN = RANK == 0

def log(*a):
    if IS_MAIN:
        print(*a, flush=True)

torch.cuda.set_device(LOCAL_RANK)

M             = os.environ["M"]
DATA          = os.environ["DATA"]
OUT           = os.environ["OUT"]
TARGET_TOTAL  = _envint("TARGET_TOTAL", default=500)
STEPS_PER_JOB = _envint("STEPS_PER_JOB", default=250)
SEQ_LEN       = _envint("SEQ_LEN", default=4096)
GRAD_ACCUM    = _envint("GRAD_ACCUM", default=4)
RANK_LORA     = _envint("LORA_RANK", default=32)
ALPHA_LORA    = _envint("LORA_ALPHA", default=32)
LR            = _envfloat("LR", default=2e-4)
NUDGE_LR      = _envfloat("NUDGE_LR", default=5e-6)
NUDGE_FRAC    = _envfloat("NUDGE_FRAC", default=0.3)
NEFTUNE_ALPHA = _envfloat("NEFTUNE_ALPHA", default=5.0)
FREEZE_FRAC   = _envfloat("EXPERT_FREEZE_FRAC", default=0.0)

log(f"=== ECO TRAIN V2 | world={WORLD_SIZE} rank={RANK} local={LOCAL_RANK} ===")
log(f"  model={M}")
log(f"  data={DATA} seq={SEQ_LEN}")
log(f"  Phase1: lr={LR}, no clipping")
log(f"  Phase2: lr={NUDGE_LR}, frac={NUDGE_FRAC}")
log(f"  NEFTune={NEFTUNE_ALPHA}, r={RANK_LORA}, alpha={ALPHA_LORA}")
log(f"  grad_accum={GRAD_ACCUM}, target={TARGET_TOTAL}")

# --------------------------------------------------------------------------- model
from transformers import AutoTokenizer, AutoModelForCausalLM

tok = AutoTokenizer.from_pretrained(M, trust_remote_code=True)
if tok.pad_token is None:
    tok.pad_token = tok.eos_token

t0 = time.time()
model = AutoModelForCausalLM.from_pretrained(
    M, trust_remote_code=True, dtype=torch.bfloat16,
    device_map={"": LOCAL_RANK}, low_cpu_mem_usage=True)
model.config.use_cache = False
log(f"MODEL LOADED in {time.time()-t0:.0f}s on cuda:{LOCAL_RANK} "
    f"{torch.cuda.get_device_name(LOCAL_RANK)}")

# --------------------------------------------------------------------------- LoRA
from peft import LoraConfig, get_peft_model

# Architecture-aware targets: Mamba-2 (in/out_proj) + attention + MLP/MoE
target = sorted({n.split(".")[-1] for n, m in model.named_modules()
                 if isinstance(m, torch.nn.Linear)} &
                {"q_proj", "k_proj", "v_proj", "o_proj",
                 "gate_proj", "up_proj", "down_proj", "in_proj", "out_proj"})
log(f"LoRA target modules: {target}")

peft_config = LoraConfig(
    r=RANK_LORA, lora_alpha=ALPHA_LORA, target_modules=target,
    lora_dropout=0.0, bias="none", task_type="CAUSAL_LM")
model = get_peft_model(model, peft_config)
model.enable_input_require_grads()

# --------------------------------------------------------- MoE weight tying init
EXPERT_RE = re.compile(r"\.experts\.\d+\.")

def _is_tie_target(mod_name):
    if ".experts." not in mod_name:
        return False
    if mod_name.endswith("up_proj.lora_A.default"):
        return True
    if mod_name.endswith("down_proj.lora_B.default"):
        return True
    return False

groups = defaultdict(list)
for name, mod in model.named_modules():
    if isinstance(mod, torch.nn.Linear) and _is_tie_target(name):
        key = EXPERT_RE.sub(".experts.#.", name)
        groups[key].append(mod)

tied_groups = 0
tied_eliminated = 0
with torch.no_grad():
    for key, mods in sorted(groups.items()):
        if len(mods) < 2:
            continue
        shapes = {tuple(m.weight.shape) for m in mods}
        if len(shapes) != 1:
            log(f"  !! SKIP group {key}: mixed shapes {shapes}")
            continue
        canonical = mods[0].weight
        mean = torch.stack([m.weight.data for m in mods], dim=0).mean(dim=0)
        canonical.data.copy_(mean)
        for m in mods[1:]:
            m.weight = canonical
            tied_eliminated += 1
        tied_groups += 1

log(f"MoE tied: {tied_groups} groups, {tied_eliminated} duplicate params collapsed")

trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
log(f"Trainable params after tying: {trainable/1e6:.2f}M")

# Expert-LoRA params for staged freeze
expert_lora_params = [p for n, p in model.named_parameters()
                      if p.requires_grad and ".experts." in n and ".lora_" in n]

# --------------------------------------------------------------------------- data
from datasets import Dataset

ds = Dataset.from_json(DATA)

def fmt(ex):
    ms = ex.get("messages") or [{"role": "user", "content": ex.get("prompt", "?")},
                                {"role": "assistant", "content": ex.get("answer", "?")}]
    return {
        "text": tok.apply_chat_template(ms, tokenize=False, add_generation_prompt=False),
        "method": ex.get("method", "other"),
    }

ds = ds.map(fmt, remove_columns=[c for c in ds.column_names if c not in ["method"]])
log(f"{len(ds)} training records")

# Extract method labels for stratification
method_labels = [ex["method"] for ex in ds]
method_dist = defaultdict(int)
for m in method_labels:
    method_dist[m] += 1
log(f"Method distribution: {dict(sorted(method_dist.items(), key=lambda x: -x[1])[:15])}")

# ------------------------------------------------------- stratified sampler
def build_stratified_index_order(labels, batch_size, seed):
    """Round-robin stratified sampling across categories."""
    by_label = defaultdict(list)
    for idx, label in enumerate(labels):
        by_label[label].append(idx)

    rng = random.Random(seed)
    for idx_list in by_label.values():
        rng.shuffle(idx_list)

    n_batches = max(1, math.ceil(len(labels) / batch_size))
    batches = [[] for _ in range(n_batches)]
    b_order = list(range(n_batches))
    rng.shuffle(b_order)

    assigned = 0
    for label in sorted(by_label.keys()):
        for idx in by_label[label]:
            batches[b_order[assigned % n_batches]].append(idx)
            assigned += 1

    order = [idx for batch in batches for idx in batch]
    return order

from torch.utils.data import Sampler

class PrecomputedOrderSampler(Sampler):
    def __init__(self, order):
        self.order = list(order)
    def __iter__(self):
        return iter(self.order)
    def __len__(self):
        return len(self.order)

# --------------------------------------------------------------------------- resume
ckpts = sorted(glob.glob(os.path.join(OUT, "checkpoint-*", "trainer_state.json")),
               key=os.path.getmtime)
RESUME = os.path.dirname(ckpts[-1]) if ckpts else None
global_step = json.load(open(ckpts[-1])).get("global_step", 0) if ckpts else 0
batch_steps = min(STEPS_PER_JOB, TARGET_TOTAL - global_step)
target_step = global_step + batch_steps
log(f"RESUME step {global_step} -> {target_step}" if RESUME else f"FRESH START -> {target_step}")

# --------------------------------------------------------- staged freeze callback
from transformers import TrainerCallback

class ExpertFreezeCallback(TrainerCallback):
    def __init__(self, params, freeze_until):
        self.params = params
        self.freeze_until = freeze_until
    def on_pre_optimizer_step(self, args, state, control, **kw):
        if state.global_step < self.freeze_until:
            for p in self.params:
                if p.grad is not None:
                    p.grad.zero_()
        return control

freeze_until = int(math.ceil(TARGET_TOTAL * FREEZE_FRAC)) if FREEZE_FRAC > 0 else 0
callbacks = []
if freeze_until > 0:
    callbacks.append(ExpertFreezeCallback(expert_lora_params, freeze_until))
    log(f"Staged expert-LoRA freeze ON: frozen until step {freeze_until}")

# --------------------------------------------------------------- two-phase setup
# Phase boundary: steps for Phase 1 vs Phase 2
nudge_start = int(TARGET_TOTAL * (1.0 - NUDGE_FRAC))

class TwoPhaseCallback(TrainerCallback):
    """Switch hyperparameters at the phase boundary.
    Phase 1: high LR, no gradient clipping
    Phase 2: low LR (nudge), gradient clipping ON, cosine schedule
    """
    def __init__(self, nudge_start, nudge_lr, phase1_lr):
        self.nudge_start = nudge_start
        self.nudge_lr = nudge_lr
        self.phase1_lr = phase1_lr
        self.switched = False

    def on_step_begin(self, args, state, control, **kw):
        if not self.switched and state.global_step >= self.nudge_start:
            self.switched = True
            # Switch to nudge LR
            optimizer = kw.get("optimizer")
            if optimizer is not None:
                for pg in optimizer.param_groups:
                    pg["lr"] = self.nudge_lr
            # Re-enable gradient clipping
            args.max_grad_norm = 1.0
            if IS_MAIN:
                print(f"\n{'='*60}", flush=True)
                print(f"PHASE 2 NUDGE START at step {state.global_step}", flush=True)
                print(f"  lr: {self.phase1_lr} -> {self.nudge_lr}", flush=True)
                print(f"  max_grad_norm: 1e9 -> 1.0", flush=True)
                print(f"{'='*60}\n", flush=True)
        return control

callbacks.append(TwoPhaseCallback(nudge_start, NUDGE_LR, LR))
log(f"Two-phase: Phase1 steps 0-{nudge_start}, Phase2 steps {nudge_start}-{TARGET_TOTAL}")

# ------------------------------------------------------------------- SFT training
from trl import SFTTrainer, SFTConfig

warmup_steps = min(30, max(1, target_step // 10))
eff_batch = 1 * GRAD_ACCUM * WORLD_SIZE

cfg = SFTConfig(
    output_dir=OUT,
    max_steps=target_step,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=GRAD_ACCUM,
    learning_rate=LR,
    lr_scheduler_type="linear",
    warmup_steps=warmup_steps,
    logging_steps=10,
    bf16=True,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    optim="adamw_torch",
    max_length=SEQ_LEN,
    dataset_text_field="text",
    packing=False,
    save_steps=50,
    save_total_limit=15,
    report_to="none",
    adam_beta1=0.9,
    adam_beta2=0.95,
    adam_epsilon=1e-8,
    weight_decay=0.0,
    max_grad_norm=1e9,  # Phase 1: clipping OFF (from VCDAD silver solution)
    neftune_noise_alpha=NEFTUNE_ALPHA,  # NEFTune embedding noise (from VCDAD)
    use_liger_kernel=True,
    ddp_find_unused_parameters=True,
    dataloader_num_workers=2,
    seed=42,
)

# Build stratified order
strat_order = build_stratified_index_order(method_labels, eff_batch, seed=42)

# Custom SFTTrainer with stratified sampling
class StratifiedSFTTrainer(SFTTrainer):
    def __init__(self, *args, stratified_order=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.stratified_order = stratified_order

    def get_train_dataloader(self):
        if self.stratified_order is None:
            return super().get_train_dataloader()
        from torch.utils.data import DataLoader
        dataloader_kwargs = {
            "batch_size": self.args.per_device_train_batch_size,
            "sampler": PrecomputedOrderSampler(self.stratified_order),
            "collate_fn": self.data_collator,
            "num_workers": self.args.dataloader_num_workers,
            "pin_memory": self.args.dataloader_pin_memory,
            "drop_last": self.args.dataloader_drop_last,
        }
        if self.args.dataloader_num_workers > 0:
            dataloader_kwargs["prefetch_factor"] = self.args.dataloader_prefetch_factor
        return DataLoader(self.train_dataset, **dataloader_kwargs)

trainer = StratifiedSFTTrainer(
    model=model, args=cfg, train_dataset=ds,
    processing_class=tok, callbacks=callbacks,
    stratified_order=strat_order,
)

log(f"TRAINING [ECO V2 TWO-PHASE]: {global_step} -> {target_step} | eff_batch="
    f"{eff_batch} (1 x ga{GRAD_ACCUM} x {WORLD_SIZE} gpu)")
log(f"  Phase1: lr={LR}, no clipping, steps 0-{nudge_start}")
log(f"  Phase2: lr={NUDGE_LR}, clipping=1.0, steps {nudge_start}-{TARGET_TOTAL}")
log(f"  NEFTune alpha={NEFTUNE_ALPHA}")

t0 = time.time()
trainer.train(resume_from_checkpoint=RESUME)
elapsed = (time.time() - t0) / 60
final_loss = next((e["loss"] for e in reversed(trainer.state.log_history) if "loss" in e), "?")
log(f"DONE {elapsed:.1f}min loss={final_loss}")

if IS_MAIN:
    model.save_pretrained(os.path.join(OUT, f"checkpoint-{target_step}"))
    print(f"Adapter saved to checkpoint-{target_step}", flush=True)
    if target_step < TARGET_TOTAL:
        print(f"NEED_RESUBMIT: target_step={target_step} target_total={TARGET_TOTAL}", flush=True)
    else:
        print(f"TARGET_REACHED: {target_step}/{TARGET_TOTAL}", flush=True)
    print("SUCCESS", flush=True)
